### ISSUE TITLE
表名和内容显示不全

### ISSUE THREAD

**Issue by xuixao** [guolindev/Glance#1]
1.数据库如果不是以.db结尾，则找不到文件
2.表名显示不全，后面是。。。
3.表中字段过多情况，显示不全

**Comment by guolindev** [comment]
Glance目前只能根据后缀去扫描数据库，没有其他方式识别，所以如果你的数据库不是以db结尾，肯定就找不到了。

至于表名显示不全，和表中字段过多显示不全的问题，能上传截图让我看一下吗？

**Comment by xuixao** [comment]
好的，郭神～见下图
![IMG_20201216_155820](https://user-images.githubusercontent.com/20995479/102321135-34f5fa00-3fb8-11eb-9edd-0c039797d3a3.jpg)

**Comment by guolindev** [comment]
你们这表的名字还真长啊，看来我不能用单行显示了。

另外表中字段过多显示不全的问题呢？有截图吗？

**Comment by guolindev** [comment]
Glance 1.0.0-alpha02版本发布了，其中修复了表名显示不全的问题，你升级一下版本号就能测试。
```
dependencies {
    // debugImplementation because Glance should only run in debug builds.
    debugImplementation 'com.glance.guolindev:glance:1.0.0-alpha02'
}
```
至于表中字段过多情况显示不全的情况，你没有给出截图，我这边无法复现这个场景，所以暂时只能忽略了。
