### ISSUE TITLE
部分数据库没有显示

### ISSUE THREAD

**Issue by zhangjingex** [guolindev/Glance#11]
使用的greendao，开始没有显示我创建的数据库，在数据库名加上 .db,就能看到了

**Comment by guolindev** [comment]
因为Glance目前的匹配测试就是以.db后缀结果去匹配的，这样搜索效率会非常快，但是同样也就出现了你的这种问题。我可能会考虑修改一下匹配机制吧。

**Comment by guolindev** [comment]
目前1.0.0版本已经修复了此问题。
