### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by yang163email** [guolindev/Glance#2]
郭shen 能不能增加一个长按复制功能。
因为有些表里面某列存的内容比较多，直接看不太方便，想复制出来查看。

**Comment by guolindev** [comment]
很好的建议，我想我应该会在1.0.0正式版的时候加入这个功能。

**Comment by NonNull7** [comment]
能不能添加一个数据导出功能

**Comment by guolindev** [comment]
数据导出功能太过模糊，不知道你具体想要的是什么效果，导出到哪里？以什么样的形式导出？

**Comment by guolindev** [comment]
@yang163email 
Glance 1.0.0-alpha02版本发布了，其中增加了你建议的长按复制功能，你升级一下版本号就能测试。

```
dependencies {
    // debugImplementation because Glance should only run in debug builds.
    debugImplementation 'com.glance.guolindev:glance:1.0.0-alpha02'
}
```

**Comment by yang163email** [comment]
@guolindev 谢谢郭shen，测试已经可以复制了

**Comment by guolindev** [comment]
OK

**Comment by quibbler01** [comment]
> @yang163email Glance 1.0.0-alpha02版本发布了，其中增加了你建议的长按复制功能，你升级一下版本号就能测试。
> 
> ```
> dependencies {
>     // debugImplementation because Glance should only run in debug builds.
>     debugImplementation 'com.glance.guolindev:glance:1.0.0-alpha02'
> }
> ```

没有添加到正式版本吗？glance:1.1.0版本没有长按复制

**Comment by guolindev** [comment]
1.1.0没有长按复制功能，因为可以双击编辑了，不需要通过长按来复制了。
