### ISSUE TITLE
1.1.0编译报错

### ISSUE THREAD

**Issue by hzl1378252** [guolindev/Glance#21]
1.0.0没有问题，今天公众号更新了1.1.0就会编译报错
设备Android7.1.2
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (30) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.paging:paging-runtime-ktx:3.1.0-alpha03.
        AAR metadata file: C:\Users\gateon\.gradle\caches\transforms-2\files-2.1\8641f3694ffa0e7b8c7f38bb29147fd7\jetified-paging-runtime-ktx-3.1.0-alpha03\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (30) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.paging:paging-runtime:3.1.0-alpha03.
        AAR metadata file: C:\Users\gateon\.gradle\caches\transforms-2\files-2.1\37af3c31b563b7374ae2fb4c22127d8f\paging-runtime-3.1.0-alpha03\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (30) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.startup:startup-runtime:1.1.0.
        AAR metadata file: C:\Users\gateon\.gradle\caches\transforms-2\files-2.1\ace8c3ee754f6ea7deeec59ee4570dd4\jetified-startup-runtime-1.1.0\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by guolindev** [comment]
这个错误你只要把你本地的compileSdkVersion指定成30或以上就可以了。

Glance本身对compileSdkVersion的版本并没有什么要求，但是从这个错误上看出来，是Glance引用的paging3库对compileSdkVersion有要求，30以下编译就会报错。

所以，如果没有什么特殊原因不能升级compileSdkVersion，只要把你本地的compileSdkVersion升级到30即可。

如果这个问题后面反馈的人很多的话，我可能会考虑降一下paging3的版本，暂时先将这个问题关闭了，谢谢反馈。

**Comment by hzl1378252** [comment]
好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月31日(星期二) 晚上9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guolindev/Glance] 1.1.0编译报错 (#21)
