### ISSUE TITLE
安装运行失败

### ISSUE THREAD

**Issue by neabea** [guolindev/Glance#3]
gradle导入成功了，但是安装运行的时候失败了，这是得翻墙么？

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.glance.guolindev:glance:1.0.0-alpha01.
     Required by:
         project :app
      > Could not resolve com.glance.guolindev:glance:1.0.0-alpha01.
         > Could not get resource 'https://maven.google.com/com/glance/guolindev/glance/1.0.0-alpha01/glance-1.0.0-alpha01.pom'.
            > Could not HEAD 'https://maven.google.com/com/glance/guolindev/glance/1.0.0-alpha01/glance-1.0.0-alpha01.pom'.
               > Connect to maven.google.com:443 [maven.google.com/172.217.160.78] failed: connect timed out

* Try:

**Comment by guolindev** [comment]
貌似是的，连接超时，翻个墙应该就好了。

**Comment by neabea** [comment]
allproject 替换maven { url 'https://maven.google.com' }为
        maven {url 'https://dl.google.com/dl/android/maven2/'}
