### ISSUE TITLE
测试中数据库崩溃被删除

### ISSUE THREAD

**Issue by jdhdevelop** [guolindev/Glance#4]
郭神你好：
我在以大概2，3秒添加一条数据这样的频率使用时，大概在添加到100到条数据后。我从自己的app返回桌面，打开Glance时，发现弹出Toast提示报错，只来得及看见“close”关键字样。然后发现数据库消失了。后面再使用，发现数据重新被创建了。原来的数据全部丢失。我不能确定是否是Glance导致的。

**Comment by guolindev** [comment]
崩溃的话有没有日志呢？

有可能是我哪里的异常没有处理，导致发生了崩溃。

但是Glance是肯定不会删除你的数据库的，目前Glance完全没有提供删除的操作，只能查询数据库，你可以看下源码，和sql相关的语句只有select的，没有delete和update的，所以肯定不会影响你的表。

**Comment by jdhdevelop** [comment]
那应该是我这边的问题。抱歉没来及查看日志。
