### ISSUE TITLE
有个提议不知当讲不当讲

### ISSUE THREAD

**Issue by kystudio** [guolindev/Glance#5]
生成的Glance入口，名字能不能跟应用关联起来，因为如果几个app同时集成这个库的话，还得一起点开看才能找到对应的？

**Comment by guolindev** [comment]
我也有想过这个功能，但是貌似让名字和应用关联并不是一件很简单的事情，因为Glance在AndroidManifest中配置的名字需要是固定的。

另外我也有参考过LeakCanary的设计，这个问题LeakCanary也并没有解决，所以我就没有把它当作必须要解决的问题了，至少在现阶段Glance还有其他许多问题优先级要更靠前一些。

**Comment by kystudio** [comment]
好的
