### ISSUE TITLE
影响部分ConstraintLayout布局界面显示

### ISSUE THREAD

**Issue by Thinkan** [guolindev/Glance#6]
你好，通过debugImplementation接入Glance在cosofteck RK3510S（Android 7.1.2）和Allwiner DS83X（Android 4.4.4）两款设备上发现，会导致部分ConstraintLayout布局错乱。

其中一个布局中间有个默认图片正常显示，但是接入库后变不能正常显示。

	  <ImageView
        android:id="@+id/default_finger_icon"
        android:layout_width="@dimen/verify_ic_width"
        android:layout_height="@dimen/verify_ic_width"
        android:src="@drawable/ic_default_finger"
        app:layout_constraintBottom_toTopOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="parent" />

我使用的参数： Android Studio 4.1

> implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

 	compileSdkVersion 29

 	buildToolsVersion "29.0.2"
 	
 	minSdkVersion 19

	targetSdkVersion 29
     
	

**最后感谢作者辛苦付出，致敬！**

**Comment by guolindev** [comment]
这是因为Glance库中引用了最新版本的constaintlayout，版本是2.0.4，高于你们项目使用的版本，gradle会以高版本为准，所以会导致整个项目工程使用的都是2.0.4版本。

这样看起来，应该是你们项目没有适配最新的constaintlayout所导致的，建议可以升级一下。

如果你们不愿意升级constaintlayout的话，也可以忽略Glance中指定的constaintlayout的版本，具体用法是这样写：

```groovy
debugImplementation('com.glance.guolindev:glance:1.0.0-alpha01') { exclude group: 'androidx.constraintlayout', module: 'constraintlayout' }
```

这样就还会以你们项目中引入的1.1.3版本为准，但是Glance在1.1.3的constrintlayout中是否还能正常显示，这个我是不确定的，你可以动手试一下。

当然我最推荐的做法还是让你们项目适配最新的constaintlayout版本。

**Comment by Thinkan** [comment]
看起来应该是constraintlayout版本问题导致的，我忽略Glance中指定的constaintlayout的版本后问题解决了。后面会考虑适配新版constaintlayout的，感谢您的解答，谢谢。
