### ISSUE TITLE
列名顺序

### ISSUE THREAD

**Issue by ghost** [guolindev/Glance#7]
郭神,通过glance看到一张表中的列名不是完全按照在创建表时的顺序排序的,看起来有些不方便.
比如一张表其中有year,month,day三个列,在使用glance查看时顺序是month,year ...其他字段,day,略有不方便,尤其在大数据量的时候,不太好对应的查看

**Comment by guolindev** [comment]
这个好像还真没有办法。

我这边也就是使用sqlite3支持的标准语法去查一张表中有哪些列，并没有做过什么排序操作，查出来是什么样，最后就怎么显示，所以如果查出来的结果就和你建表时候顺序不一致，我也没办法做调整。

这个issue我先保留一段时间吧，如果哪位朋友知道如何按原有建表字段的顺序去查出来所有的列，可以帮忙支支招。

**Comment by ghost** [comment]
郭神,刚刚发现在android inspector中列的顺序也是乱的,看来标准认为不用排序.

**Comment by guolindev** [comment]
因为数据库表的其中一项特性就是，行无序性和列无序性，所以从排序的角度上来说显然是无意义的，但是如果是为了方便查看的话，一个合理的排序确实更加人性化，只是我不知道是否有这个接口可以实现。
