### ISSUE TITLE
非AndroidX项目跑不起来

### ISSUE THREAD

**Issue by GospelHW** [guolindev/Glance#8]
![image](https://user-images.githubusercontent.com/24928406/103070142-d950ef80-45fb-11eb-988a-4bca04ee4dc2.png)

**Comment by guolindev** [comment]
对，主页文档上已经说明了，仅支持AndroidX。

Note that Glance only supports AndroidX projects. Android-Support projects can't use this library, and have no plan to support for them in the future release either.
