### ISSUE TITLE
啥时候支持设备db的一瞥啊？

### ISSUE THREAD

**Issue by GospelHW** [guolindev/Glance#9]
目前只支持应用自己的db一瞥，意味着每个app都要加这个依赖，或者copy到你加了工具的应用目录下，略嫌麻烦。
如果能读取整个设备的岂不美哉

**Comment by guolindev** [comment]
从Android 10开始，scoped storage功能已经限制应用程序去读取整个设备的sd卡了，从Android 11开始，scoped storage被强制使用，所以你建议的这个功能不可能实现。

**Comment by GospelHW** [comment]
那是不是意味着，sdcard这块防卸载导致数据的最后保障在android已经不存在了？在和iOS看起么？将来是不是永远都无法保证客户端数据不丢失了

**Comment by guolindev** [comment]
你可以备份到云端，不要依赖用户的手机做存储备份，你永远无法知道这个数据会不会被用户手动删除。

**Comment by GospelHW** [comment]
> 你可以备份到云端，不要依赖用户的手机做存储备份，你永远无法知道这个数据会不会被用户手动删除。

嗯嗯，强依赖网络也存在客户端网络也是永远无法保证的问题
